### ISSUE TITLE
Bad news

### ISSUE THREAD

**Issue by SpeckyYT** [SpeckyYT/gd_sfx#14]
I got banned from discord for apparently being underaged 💀💀💀💀 Bro, I sent them my ID like 3 times already 💀💀💀

**Comment by ggodpl** [comment]
too many "I'm not 13" jokes

**Comment by itsmebombie** [comment]
bro got discor'd

**Comment by kr8gz** [comment]
💀💀💀💀💀💀💀💀💀💀💀💀

**Comment by ivythegreenest** [comment]
i miss you specky

**Comment by ggodpl** [comment]
make an alt account or something

**Comment by kr8gz** [comment]
@SpeckyYT i think we can delete the old code from rwrt and merge to master now, what do you think

**Comment by SpeckyYT** [comment]
yeah, I was going to say the same, it's good to go

**Comment by kr8gz** [comment]
69 commits ahead of master lmao

**Comment by kr8gz** [comment]
fuck i didnt mean to close this

**Comment by ivythegreenest** [comment]
@SpeckyYT make new alt Account....

**Comment by kr8gz** [comment]
yeah can you make an alt account i think waiting for discord support is a waste of time

**Comment by Poppy-joe** [comment]
mods, get his ass 
![IMG_20240118_233312](https://github.com/SpeckyYT/gd_sfx/assets/157075231/bb4a5a68-67cc-46b8-92b0-6207cd5e5110)

**Comment by ivythegreenest** [comment]
how about you shut your ass

**Comment by Poppy-joe** [comment]
whats my ass gotta do with this >:((((

**Comment by ivythegreenest** [comment]
jiggle

**Comment by Poppy-joe** [comment]
yes pookie bear just for you 😘😘

**Comment by 3pm-on-github** [comment]
close this pls

**Comment by itsmebombie** [comment]
bad news

**Comment by 3pm-on-github** [comment]
just close this pls ;-;

**Comment by kr8gz** [comment]
close ur mouth pls

**Comment by 3pm-on-github** [comment]
@SpeckyYT close this

**Comment by SpeckyYT** [comment]
this will only be closed once I get my account back

**Comment by 3pm-on-github** [comment]
ohok

**Comment by 3pm-on-github** [comment]
idk

**Comment by SpeckyYT** [comment]
the king is back

**Comment by SevenworksDev** [comment]
commenting cuz more bad news, specky hit me at a fan meetup. exposed

**Comment by SpeckyYT** [comment]
I remember that as if it was yesterday

**Comment by ivythegreenest** [comment]
bad news: i ripped off my ballsack after itching it

**Comment by SevenworksDev** [comment]
bad news: sevenworks servers down again, chicago police reported that sevenworks was arrested for kidnapping of a newborn child to record the infamous "ash baby" pictures
![007](https://github.com/SpeckyYT/gd_sfx/assets/91027492/05f031da-e135-4c42-9af6-48e641bb6077)
![6e6](https://github.com/SpeckyYT/gd_sfx/assets/91027492/ab91da97-b1d2-4d75-a828-4a15f131634d)
